dependencies:
  - aiohttp==3.8.4
  - altair==5.1.2
  - beautifulsoup4==4.11.1
  - docx2txt==0.8
  - Flask==2.2.2
  - flask_cors==4.0.0
  - ipython==8.10.0
  - ipywidgets==7.6.5
  - langchain==0.0.306
  - matplotlib==3.7.2
  - networkx==3.1
  - nltk==3.7
  - numpy==1.23.5
  - openai==0.28.1
  - pandas==1.5.3
  - PyPDF2==3.0.1
  - PyYAML==6.0
  - PyYAML==6.0.1
  - Requests==2.31.0
  - scikit_learn==1.2.1
  - scipy==1.10.0
  - smokey==0.1
  - streamlit==1.27.1
  - streamlit_chat==0.1.1
  - tenacity==8.2.2
  - termcolor==2.3.0
  - tiktoken==0.5.1
  - tqdm==4.64.1
  - watermark==2.4.2
  - wget==3.2
