dependencies:
  - aiohttp==3.8.5
  - altair==5.2.0
  - beautifulsoup4==4.12.3
  - docx2txt==0.8
  - Flask==2.2.2
  - flask_cors==4.0.0
  - ipython==8.12.3
  - ipywidgets==8.0.4
  - langchain==0.1.9
  - matplotlib==3.7.2
  - networkx==3.1
  - nltk==3.8.1
  - numpy==1.23.5
  - openai==1.12.0
  - pandas==2.0.3
  - PyPDF2==3.0.1
  - PyYAML==6.0.1
  - Requests==2.31.0
  - scikit_learn==1.3.0
  - scipy==1.12.0
  - smokey==0.1
  - streamlit==1.31.1
  - streamlit_chat==0.1.1
  - tenacity==8.2.2
  - termcolor==2.4.0
  - tiktoken==0.3.3
  - tqdm==4.65.0
  - watermark==2.4.3
  - wget==3.2
